// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3nQ-PUyhkhswudJPxWI6ZXkGel1oDXHU',
    appId: '1:478582556390:web:0c8c965ca1a7b6881cdd27',
    messagingSenderId: '478582556390',
    projectId: 'muistiinpanosovellus',
    authDomain: 'muistiinpanosovellus.firebaseapp.com',
    storageBucket: 'muistiinpanosovellus.firebasestorage.app',
    measurementId: 'G-GHDFEFXM9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBAEn11tBBNCUnOd644QXWYdHwpC0E5Ss',
    appId: '1:478582556390:android:c1900277411a44fa1cdd27',
    messagingSenderId: '478582556390',
    projectId: 'muistiinpanosovellus',
    storageBucket: 'muistiinpanosovellus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEDXrkdo4LM7ruwSmXmG7PqJEt2LUpQIM',
    appId: '1:478582556390:ios:086f633974fadea21cdd27',
    messagingSenderId: '478582556390',
    projectId: 'muistiinpanosovellus',
    storageBucket: 'muistiinpanosovellus.firebasestorage.app',
    iosBundleId: 'com.example.muistiinpanosovellus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEDXrkdo4LM7ruwSmXmG7PqJEt2LUpQIM',
    appId: '1:478582556390:ios:086f633974fadea21cdd27',
    messagingSenderId: '478582556390',
    projectId: 'muistiinpanosovellus',
    storageBucket: 'muistiinpanosovellus.firebasestorage.app',
    iosBundleId: 'com.example.muistiinpanosovellus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3nQ-PUyhkhswudJPxWI6ZXkGel1oDXHU',
    appId: '1:478582556390:web:897def7773b1755b1cdd27',
    messagingSenderId: '478582556390',
    projectId: 'muistiinpanosovellus',
    authDomain: 'muistiinpanosovellus.firebaseapp.com',
    storageBucket: 'muistiinpanosovellus.firebasestorage.app',
    measurementId: 'G-79PVBZVKQP',
  );
}
